apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: cluster-agent
  name: cluster-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cluster-agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-nginx-network: "true"
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: cluster-agent
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql_8
            - name: DB_NAME
              value: saasconnector
            - name: DB_PASSWORD
              value: "123456789"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: NEW_RELIC_LICENSE_KEY
              value: a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: tiggomark/clusteragent:latest
          name: cluster-agent
          ports:
            - containerPort: 8089
              hostPort: 8089
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "398458880"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: cluster-agent-claim0
            - mountPath: /var/temp
              name: cluster-agent-claim1
      hostname: clusteragent-hostname
      restartPolicy: Always
      volumes:
        - name: cluster-agent-claim0
          persistentVolumeClaim:
            claimName: cluster-agent-claim0
        - name: cluster-agent-claim1
          persistentVolumeClaim:
            claimName: cluster-agent-claim1
status: {}
