apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: crm
  name: crm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-nginx-network: "true"
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: crm
    spec:
      containers:
        - env:
            - name: ESPOCRM_ADMIN_PASSWORD
              value: leghacy123
            - name: ESPOCRM_ADMIN_USERNAME
              value: admin
            - name: ESPOCRM_DATABASE_HOST
              value: db_crm
            - name: ESPOCRM_DATABASE_NAME
              value: DB_CRM_2d092597_6d9b_4263_8a9f_0fda9c2451a2
            - name: ESPOCRM_DATABASE_PASSWORD
              value: "123456789"
            - name: ESPOCRM_DATABASE_USER
              value: root
            - name: ESPOCRM_SITE_URL
              value: http://tiggo-crm:8082
          image: tiggomark/crm:latest
          name: crm
          ports:
            - containerPort: 80
              hostPort: 8082
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "268435456"
          volumeMounts:
            - mountPath: /var/www/html
              name: tiggocrm
            - mountPath: /var/upload
              name: crm-upload-files
      hostname: tiggo-crm
      restartPolicy: Always
      volumes:
        - name: tiggocrm
          persistentVolumeClaim:
            claimName: tiggocrm
        - name: crm-upload-files
          persistentVolumeClaim:
            claimName: crm-upload-files
status: {}
