apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: db-crm
  name: db-crm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-crm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: db-crm
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: DB_CRM_2d092597_6d9b_4263_8a9f_0fda9c2451a2
            - name: MYSQL_PASSWORD
              value: "123456789"
            - name: MYSQL_ROOT_PASSWORD
              value: "123456789"
            - name: MYSQL_USER
              value: admin
          image: mysql:8
          name: db-crm
          ports:
            - containerPort: 3306
              hostPort: 4502
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "419430400"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-crm-data-cluster1
      hostname: db_crm
      restartPolicy: Always
      volumes:
        - name: db-crm-data-cluster1
          persistentVolumeClaim:
            claimName: db-crm-data-cluster1
status: {}
