version: '3.7'

services:


  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer-hostname
    restart: unless-stopped
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - tiggomark_network



  projects:
    image: tiggomark/projects:latest
    hostname: projects-hostname

    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      TIGGO_SITENAME: 'Tiggomark'
      TIGGO_DB_HOST: 'tiggomark_saas_connector_db'
      SAAS_CONNECTOR_URL: 'http://saas-connector-hostname:8080'
      SAAS_CONNECTOR_APP_TOKEN: 'app-token'
      TIGGO_DB_USER: 'root'
      TIGGO_DB_PASSWORD: '123456789'
      TIGGO_DB_PORT: '3306'
      TIGGO_DB_DATABASE: 'saasconnector'
      TIGGO_DEFAULT_TIMEZONE: 'Europe/Stockholm'
      TIGGO_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'
      TIGGO_SESSION_EXPIRATION: 28800
    volumes:
      - projects_public_user-files:/var/www/html/public/userfiles
      - projects_user-files:/var/www/html/userfiles
    depends_on:
        - projects_db
    networks:
      - tiggomark_network
      - nginx_network



  saas_connector:
    image: tiggomark/saas-connector:1.0.1
    hostname: saas-connector-hostname
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '356M'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NEW_RELIC_LICENSE_KEY: 'a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      DB_HOST: 'tiggomark_saas_connector_db'
      DB_PORT: '3306'
      DB_NAME: 'saasconnector'
      DB_USERNAME: 'root'
      DB_PASSWORD: '123456789'
    depends_on:
        - saas_connector_db
    networks:
      - tiggomark_network
      - nginx_network
    ports:
      - target: 8080
        published: 8085
        protocol: tcp
        mode: ingress

  saas_connector_db:
    image: mysql:8
    hostname: tiggomark_saas_connector_db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.75'
          memory: '512M'
    environment:
      MYSQL_DATABASE: 'saasconnector'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      - saas_connector_db_data_cl:/var/lib/mysql
    ports:
      - target: 3306
        published: 4500
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network

  nginx:
    image: nginx
    hostname: nginx_infra
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/fullchain.pem:/etc/letsencrypt/live/tiggomark.com.br/fullchain.pem
      - ./ssl/privkey.pem:/etc/letsencrypt/live/tiggomark.com.br/privkey.pem
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress

      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    networks:
      - tiggomark_network
      - nginx_network




volumes:
  portainer_data:
  projects_user-files:
  projects_public_user-files:
  projects_db_data_cl:
  saas_connector_db_data_cl:
  clickhouse_data:


networks:
  tiggomark_network:
    driver: overlay
    ipam:
        config:
            - subnet: 10.0.9.0/24
    attachable: true

  nginx_network:
    driver: overlay






