version: '3.7'

services:


  projects_db:
    image: mysql:8.0
    hostname: tiggomark-projects-db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      MYSQL_DATABASE: 'saasconnector'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      - cl_projects_db_data:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network


  projects:
    image: tiggomark/projects:latest
    hostname: projects-hostname

    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      TIGGO_SITENAME: 'Tiggomark'
      TIGGO_DB_HOST: 'tiggomark-projects-db'
      SAAS_CONNECTOR_URL: 'http://localhost:8080'
      SAAS_CONNECTOR_APP_TOKEN: 'app-token'
      TIGGO_DB_USER: 'root'
      TIGGO_DB_PASSWORD: '123456789'
      TIGGO_DB_PORT: '3306'
      TIGGO_DB_DATABASE: 'saasconnector'
      TIGGO_DEFAULT_TIMEZONE: 'Europe/Stockholm'
      TIGGO_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'
      TIGGO_SESSION_EXPIRATION: 28800
    volumes:
      - projects_public_user-files:/var/www/html/public/userfiles
      - projects_user-files:/var/www/html/userfiles
    depends_on:
        - projects_db
    networks:
      - tiggomark_network



  saas_connector:
    image: tiggomark/saas-connector:latest
    hostname: saas-connector-hostname
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      USER_WEBHOOK: 'http://projects-hostname/api/userwebhook'
      DB_HOST: 'tiggomark_saas_connector_db'
      ASAAS_URL: 'https://sandbox.asaas.com'
      DB_PORT: '3306'
      DB_NAME: 'saasconnector'
      DB_USERNAME: 'root'
      DB_PASSWORD: '123456789'
    depends_on:
        - saas_connector_db
    networks:
      - tiggomark_network
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress

  saas_connector_db:
    image: mysql:8
    hostname: tiggomark_saas_connector_db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      MYSQL_DATABASE: 'saasconnector'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      - cl_saas_connector_db_data:/var/lib/mysql
    ports:
      - target: 3306
        published: 4500
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network

  nginx:
    image: nginx
    hostname: nginx_infra
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/fullchain.pem:/etc/letsencrypt/live/tiggomark.com.br/fullchain.pem
      - ./ssl/privkey.pem:/etc/letsencrypt/live/tiggomark.com.br/privkey.pem
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress

      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    networks:
      - tiggomark_network

volumes:
  projects_user-files:
  projects_public_user-files:
  cl_projects_db_data:
  cl_saas_connector_db_data:


networks:
  tiggomark_network:
    driver: overlay
    ipam:
        config:
            - subnet: 10.0.9.0/24
    attachable: true






