version: '3.3'

services:

  projects:
    image: tiggomark/projects:latest
    container_name: tiggomark_projects
    environment:
      #TIGGO_APP_URL: 'https://vpn.tiggomark.com.br'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
      TIGGO_SITENAME: 'Tiggomark'                                         # Name of your site, can be changed later
      TIGGO_DB_HOST: 'tiggomark_projects_db'                                    # Database host, derived from container_name in tiggomark_db container
      SAAS_CONNECTOR_URL: 'tiggomark_saas_connector:8080'
      SAAS_CONNECTOR_APP_TOKEN: 'app-token'
      TIGGO_DB_USER: 'root'
      TIGGO_DB_PASSWORD: '321.qwerty'
      TIGGO_DB_PORT: 3309
      TIGGO_DB_DATABASE: 'tiggomark'
      TIGGO_DEFAULT_TIMEZONE: 'Europe/Stockholm'                         # Set default server timezone
      TIGGO_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'         # Salting sessions. Replace with a strong password
      TIGGO_SESSION_EXPIRATION: 28800                                    # How many seconds after inactivity should we logout?  28800seconds = 8hours
    volumes:
      - projects_public_user-files:/var/www/html/public/userfiles
      - projects_user-files:/var/www/html/userfiles
    ports:
      - "8081:80"
    depends_on:
      - projects_db

  projects_db:
    image: mysql:8.0
    container_name: tiggomark_projects_db
    volumes:
      - projects_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '321.qwerty'
      MYSQL_DATABASE: 'tiggomark'
      MYSQL_USER: 'admin'
      MYSQL_TCP_PORT: '3309'
      MYSQL_PASSWORD: '321.qwerty'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3309:3309"


  saas_connector:
    image: tiggomark/saas-connector:latest
    container_name: tiggomark_saas_connector
    environment:
      DB_HOST: localhost
      DB_PORT: 4500
      DB_NAME: saasconnector
      DB_USERNAME: root
      DB_PASSWORD: 123456789

    depends_on:
      - saas_connector_db
    ports:
      - "8080:8080"

  saas_connector_db:
    image: mysql:8
    container_name: tiggomark_saas_connector_db
    environment:
      MYSQL_DATABASE: saasconnector
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "4500:3306"
    volumes:
      - saas_connector_db_data:/var/lib/mysql

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/fullchain.pem:/etc/letsencrypt/live/tiggomark.com.br/fullchain.pem
      - ./ssl/privkey.pem:/etc/letsencrypt/live/tiggomark.com.br/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tiggomark


volumes:
  projects_user-files:
  projects_public_user-files:
  projects_db_data:
  saas_connector_db_data:





