version: '3.7'

services:


  cluster_agent:
    hostname: clusteragent-hostname
    image: tiggomark/clusteragent:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '380M'

    ports:
      - target: 8089
        published: 8089
        protocol: tcp
        mode: ingress

    environment:
      SPRING_PROFILES_ACTIVE: prod
      NEW_RELIC_LICENSE_KEY: 'a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      DB_HOST: 'tiggomark_saas_connector_db'
      DB_PORT: '3306'
      DB_NAME: 'saasconnector'
      DB_USERNAME: 'root'
      DB_PASSWORD: '123456789'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/temp:/var/temp

    networks:
      - tiggomark_network
      - nginx_network


  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer-hostname
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - tiggomark_network



  projects:
    image: tiggomark/projects:latest
    hostname: projects-hostname

    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      TIGGO_SITENAME: 'Tiggomark'
      TIGGO_DEBUG: 0
      TIGGO_DB_HOST: 'tiggomark_saas_connector_db'
      TIGGO_SAAS_CONNECTOR_URL: 'http://saas-connector-hostname:8080'
      TIGGO_SAAS_CONNECTOR_APP_TOKEN: '3869c08a-306b-40ff-960c-221c2c9b04d9'
      TIGGO_SAAS_CONNECTOR_APP_ID: 'APP_E5722BC7FD884EC4A8D6ABFC76A62B17'
      TIGGO_DB_USER: 'root'
      TIGGO_DB_PASSWORD: 123456789
      TIGGO_DB_PORT: '3306'
      TIGGO_DB_DATABASE: 'saasconnector'
      TIGGO_DEFAULT_TIMEZONE: 'Europe/Stockholm'
      TIGGO_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'
      TIGGO_SESSION_EXPIRATION: 28800
    volumes:
      - projects_public_user-files:/var/www/html/public/userfiles
      - projects_user-files:/var/www/html/userfiles
    depends_on:
        - projects_db
    networks:
      - tiggomark_network
      - nginx_network



  saas_connector:
    image: tiggomark/saasconnector:latest
    hostname: saas-connector-hostname
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NEW_RELIC_LICENSE_KEY: 'a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      DB_HOST: 'tiggomark_saas_connector_db'
      DB_PORT: '3306'
      DB_NAME: 'saasconnector'
      DB_USERNAME: 'root'
      DB_PASSWORD: 123456789
    depends_on:
        - saas_connector_db
    networks:
      - tiggomark_network
      - nginx_network
    ports:
      - target: 8080
        published: 8085
        protocol: tcp
        mode: ingress

  saas_connector_db:
    image: mysql:8
    hostname: tiggomark_saas_connector_db
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    environment:
      MYSQL_DATABASE: 'saasconnector'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - saas_connector_db_data_cl:/var/lib/mysql
    ports:
      - target: 3306
        published: 4500
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network


  nginx:
    image: nginx
    hostname: nginx_infra
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/fullchain.pem:/etc/letsencrypt/live/tiggomark.com.br/fullchain.pem
      - ./ssl/privkey.pem:/etc/letsencrypt/live/tiggomark.com.br/privkey.pem
      - ./ssl/projects/fullchain.pem:/etc/letsencrypt/live/projects.tiggomark.com.br/fullchain.pem
      - ./ssl/projects/privkey.pem:/etc/letsencrypt/live/projects.tiggomark.com.br/privkey.pem
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress

      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    networks:
      - tiggomark_network
      - nginx_network

  espocrm-daemon:
    image: tiggomark/crm:latest
    volumes:
      - tiggocrm:/var/www/html

    entrypoint: docker-daemon.sh
    networks:
      - tiggomark_network
      - nginx_network

  espocrm-websocket:
    image: tiggomark/crm:latest
    hostname: espocrm-websocket
    container_name: espocrm-websocket
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://espocrm-websocket:8083"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - tiggocrm:/var/www/html
    entrypoint: docker-websocket.sh
    ports:
      - target: 8080
        published: 8083
        protocol: tcp
        mode: ingress

    networks:
      - tiggomark_network
      - nginx_network

  crm:
    image: tiggomark/crm:latest
    hostname: tiggo-crm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    networks:
      - tiggomark_network
      - nginx_network
    environment:
      ESPOCRM_DATABASE_HOST: 'tiggomark_saas_connector_db'
      ESPOCRM_DATABASE_USER: root
      ESPOCRM_DATABASE_NAME: DB_espocrm
      ESPOCRM_DATABASE_PASSWORD: 123456789
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://tiggo-crm:8082"
    volumes:
      - tiggocrm:/var/www/html
      - upload_files:/var/upload

    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress






volumes:
  portainer_data:
  projects_user-files:
  projects_public_user-files:
  projects_db_data_cl:
  saas_connector_db_data_cl:
  clickhouse_data:
  tiggocrm:
  upload_files:



networks:
  tiggomark_network:
    driver: overlay
    ipam:
        config:
            - subnet: 10.0.9.0/24
    attachable: true

  nginx_network:
    driver: overlay






