version: '3.7'

services:

  mysql_db_5_7:
    image: mysql:5.7.41
    hostname: mysql_db_5_7
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '300M'
    environment:
      MYSQL_DATABASE: DB_markee
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - mysql_db_5_7_dt:/var/lib/mysql
    ports:
      - target: 3306
        published: 4501
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network
      - nginx_network

  postgres:
    image: postgres:12
    #hostname: postgres-hostname
    deploy:
      replicas: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=123456789
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network
      - nginx_network

  redis:
    image: redis:alpine
    hostname: redis-hostname
    deploy:
      replicas: 1
    #command: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]
    environment:
      - REDIS_PASSWORD=123456789
    volumes:
      - redis_data_cl:/data
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network
      - nginx_network

  base:
    image: tiggomark/chatplus:latest
    volumes:
      - chatplus_data:/app/storage
    networks:
      - tiggomark_network
      - nginx_network

  chatplus:
    image: tiggomark/chatplus:latest
    hostname: chatplus-hostname
    deploy:
      replicas: 1
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      - FRONTEND_URL=http://chatplus.tiggomark.com.br
      - NODE_ENV=production
      - SECRET_KEY_BASE=secret
      - FORCE_SSL=false
      - DEFAULT_LOCALE=pt
      - RAILS_ENV=production
      - REDIS_URL=redis://redis-hostname:6379
      - INSTALLATION_ENV=docker
      - HELPCENTER_URL=http://chatplus.tiggomark.com.br
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=123456789
      - SMTP_DOMAIN=tiggoprojects@zohomail.com
      - SMTP_ADDRESS=smtp.zoho.com
      - SMTP_PORT=587
      - SMTP_USERNAME=tiggoprojects@zohomail.com
      - SMTP_PASSWORD=leghacy123
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - SMTP_TLS=true
      - ACTIVE_STORAGE_SERVICE=local
      - FB_VERIFY_TOKEN=@Leghacy171296
      - FB_APP_SECRET=9beb45b993cd43768941415fcef1fe69
      - FB_APP_ID=1579473235907233
      - NEW_RELIC_LICENSE_KEY='a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
      - NEW_RELIC_APPLICATION_LOGGING_ENABLED=true
    command: [ 'bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]

    networks:
      - tiggomark_network
      - nginx_network

  sidekiq:
    image: chatwoot/chatwoot:latest
    deploy:
      replicas: 1
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: [ 'bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml' ]
    networks:
      - tiggomark_network
      - nginx_network


   ###################################################

  cluster_agent:
    hostname: clusteragent-hostname
    image: tiggomark/clusteragent:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '380M'

    ports:
      - target: 8089
        published: 8089
        protocol: tcp
        mode: ingress

    environment:
      SPRING_PROFILES_ACTIVE: prod
      NEW_RELIC_LICENSE_KEY: 'a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      DB_HOST: 'tiggomark_saas_connector_db'
      DB_PORT: '3306'
      DB_NAME: 'saasconnector'
      DB_USERNAME: 'root'
      DB_PASSWORD: '123456789'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/temp:/var/temp

    networks:
      - tiggomark_network
      - nginx_network


  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer-hostname
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - tiggomark_network



  projects:
    image: tiggomark/projects:latest
    hostname: projects-hostname

    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    environment:
      TIGGO_SITENAME: 'Tiggomark'
      TIGGO_DEBUG: 0
      TIGGO_DB_HOST: 'tiggomark_saas_connector_db'
      TIGGO_SAAS_CONNECTOR_URL: 'http://saas-connector-hostname:8080'
      TIGGO_SAAS_CONNECTOR_APP_TOKEN: '217dc0d4-a190-480e-b871-ebf2adec7055'
      TIGGO_SAAS_CONNECTOR_APP_ID: 'APP_0286C4A3E1E94998BD79A1EEACA5903C'
      TIGGO_DB_USER: 'root'
      TIGGO_DB_PASSWORD: 123456789
      TIGGO_DB_PORT: '3306'
      TIGGO_DB_DATABASE: 'saasconnector'
      TIGGO_DEFAULT_TIMEZONE: 'Europe/Stockholm'
      TIGGO_SESSION_PASSWORD: 'GD8Fozemg3AqM9my86TTfgTeGPXXkPF7'
      TIGGO_SESSION_EXPIRATION: 28800
    volumes:
      - projects_public_user-files:/var/www/html/public/userfiles
      - projects_user-files:/var/www/html/userfiles

    networks:
      - tiggomark_network
      - nginx_network




  markee:
      image: tiggomark/markee:latest
      hostname: markee-hostname
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: '0.5'
            memory: '512M'
      ports:
        - target: 80
          published: 8086
          protocol: tcp
          mode: ingress

      environment:
        MAUTIC_DB_HOST: mysql_db_5_7
        MAUTIC_DB_PASSWORD: 123456789
        MAUTIC_DB_USER: root
        MAUTIC_DB_PORT: 3306
        MAUTIC_DB_NAME: DB_markee

      networks:
        - tiggomark_network
        - nginx_network


  saas_connector:
    image: tiggomark/saasconnector:latest
    hostname: saas-connector-hostname
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      NEW_RELIC_LICENSE_KEY: 'a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      DB_HOST: 'tiggomark_saas_connector_db'
      DB_PORT: '3306'
      DB_NAME: 'saasconnector'
      DB_USERNAME: 'root'
      DB_PASSWORD: 123456789
    depends_on:
        - saas_connector_db

    volumes:
      - saas_connector_files:/var/uploadfiles
    networks:
      - tiggomark_network
      - nginx_network
    ports:
      - target: 8080
        published: 8085
        protocol: tcp
        mode: ingress

  saas_connector_db:
    image: mysql:8
    hostname: tiggomark_saas_connector_db
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=120 --innodb_buffer_pool_size=256M --innodb_log_file_size=100M --innodb_flush_log_at_trx_commit=2 --innodb_flush_method=O_DIRECT_NO_FSYNC
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    environment:
      MYSQL_DATABASE: 'saasconnector'
      MYSQL_INIT_CONNECT: "SET SESSION wait_timeout = 300;"
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - saas_connector_db_data_cl:/var/lib/mysql
    ports:
      - target: 3306
        published: 4500
        protocol: tcp
        mode: ingress
    networks:
      - tiggomark_network


  nginx:
    image: nginx
    hostname: nginx_infra
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/fullchain.pem:/etc/letsencrypt/live/tiggomark.com.br/fullchain.pem
      - ./ssl/privkey.pem:/etc/letsencrypt/live/tiggomark.com.br/privkey.pem
      - ./ssl/projects/fullchain.pem:/etc/letsencrypt/live/projects.tiggomark.com.br/fullchain.pem
      - ./ssl/projects/privkey.pem:/etc/letsencrypt/live/projects.tiggomark.com.br/privkey.pem
      - ./ssl/markee/fullchain.pem:/etc/letsencrypt/live/markee.tiggomark.com.br/fullchain.pem
      - ./ssl/markee/privkey.pem:/etc/letsencrypt/live/markee.tiggomark.com.br/privkey.pem
      - ./ssl/crm/fullchain.pem:/etc/letsencrypt/live/crm.tiggomark.com.br/fullchain.pem
      - ./ssl/crm/privkey.pem:/etc/letsencrypt/live/crm.tiggomark.com.br/privkey.pem
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress

      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    networks:
      - tiggomark_network
      - nginx_network

  espocrm-daemon:
    image: tiggomark/crm:latest
    volumes:
      - tiggocrm:/var/www/html

    entrypoint: docker-daemon.sh
    networks:
      - tiggomark_network
      - nginx_network

  espocrm-websocket:
    image: tiggomark/crm:latest
    hostname: espocrm-websocket
    container_name: espocrm-websocket
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://espocrm-websocket:8083"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - tiggocrm:/var/www/html
    entrypoint: docker-websocket.sh
    ports:
      - target: 8080
        published: 8083
        protocol: tcp
        mode: ingress

    networks:
      - tiggomark_network
      - nginx_network

  crm:
    image: tiggomark/crm:latest
    hostname: tiggo-crm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
    networks:
      - tiggomark_network
      - nginx_network
    environment:
      ESPOCRM_DATABASE_HOST: 'tiggomark_saas_connector_db'
      ESPOCRM_DATABASE_USER: root
      ESPOCRM_DATABASE_NAME: DB_CRM_tiggomark
      ESPOCRM_DATABASE_PASSWORD: 123456789
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://tiggo-crm:8082"
    volumes:
      - tiggocrm:/var/www/html
      - crm_upload_files:/var/upload

    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress


  intersaas:
      image: tiggomark/intersaas:latest
      hostname: intersaas
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: '0.5'
            memory: '512M'
      ports:
        - target: 8080
          published: 8084
          protocol: tcp
          mode: ingress

      environment:
        #NEW_RELIC_LICENSE_KEY: 'a7befd5b85c71de724a6fcf7c4f13e91FFFFNRAL'
        SPRING_PROFILES_ACTIVE: prod
        DB_HOST: tiggomark_saas_connector_db
        DB_USERNAME: root
        DB_PASSWORD: 123456789
        DB_PORT: 3306
        DB_NAME: SAAS_INTEGRATOR_ROOT_DB

      networks:
        - tiggomark_network
        - nginx_network



volumes:
  postgres_data:
  chatplus_data:
  portainer_data:
  projects_user-files:
  projects_public_user-files:
  projects_db_data_cl:
  saas_connector_db_data_cl:
  clickhouse_data:
  tiggocrm:
  crm_upload_files:
  saas_connector_files:
  redis_data_cl:
  mysql_db_5_7_dt:



networks:
  tiggomark_network:
    driver: overlay
    ipam:
        config:
            - subnet: 10.0.9.0/24
    attachable: true

  nginx_network:
    driver: overlay






