apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: espocrm-daemon
  name: espocrm-daemon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: espocrm-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-nginx-network: "true"
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: espocrm-daemon
    spec:
      containers:
        - command:
            - docker-daemon.sh
          image: tiggomark/crm:latest
          name: espocrm-daemon
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: tiggocrm
      restartPolicy: Always
      volumes:
        - name: tiggocrm
          persistentVolumeClaim:
            claimName: tiggocrm
status: {}
