apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: intersaas
  name: intersaas
  namespace: default
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8080
  selector:
    io.kompose.service: intersaas
status:
  loadBalancer: {}
