apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: markee
  name: markee
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: markee
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-nginx-network: "true"
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: markee
    spec:
      containers:
        - env:
            - name: MAUTIC_DB_HOST
              value: mysql_db_5_7
            - name: MAUTIC_DB_NAME
              value: DB_markee
            - name: MAUTIC_DB_PASSWORD
              value: "123456789"
            - name: MAUTIC_DB_PORT
              value: "3306"
            - name: MAUTIC_DB_USER
              value: root
          image: tiggomark/markee:latest
          name: markee
          ports:
            - containerPort: 80
              hostPort: 8086
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
          volumeMounts:
            - mountPath: /var/www/html
              name: markee-html-files
      hostname: markee-hostname
      restartPolicy: Always
      volumes:
        - name: markee-html-files
          persistentVolumeClaim:
            claimName: markee-html-files
status: {}
