apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-8
  name: mysql_8
  namespace: default
spec:
  ports:
    - name: "4500"
      port: 4500
      targetPort: 3306
  selector:
    io.kompose.service: mysql-8
status:
  loadBalancer: {}
