apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: portainer
    spec:
      containers:
        - image: portainer/portainer-ce:latest
          name: portainer
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: portainer-claim0
            - mountPath: /data
              name: portainer-data
      hostname: portainer-hostname
      restartPolicy: Always
      volumes:
        - name: portainer-claim0
          persistentVolumeClaim:
            claimName: portainer-claim0
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-data
status: {}
