apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: saas-connector
  name: saas-connector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: saas-connector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/tiggomark-infra-nginx-network: "true"
        io.kompose.network/tiggomark-infra-tiggomark-network: "true"
        io.kompose.service: saas-connector
    spec:
      containers:
        - image: tiggomark/saasconnector:latest
          name: saas-connector
          ports:
            - containerPort: 8089
              hostPort: 8085
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "838860800"
          volumeMounts:
            - mountPath: /var/uploadfiles
              name: saas-connector-files
      hostname: saas-connector-hostname
      restartPolicy: Always
      volumes:
        - name: saas-connector-files
          persistentVolumeClaim:
            claimName: saas-connector-files
status: {}
