apiVersion: v1
kind: Service
metadata:
  name: saas-connector-lb
  annotations:
    metallb.universe.tf/address-pool: production
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: saas-connector
  type: LoadBalancer