apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  selector:
    app: portainer
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  type: LoadBalancer
