name: Update Cluster

on:
  push:
    branches:
      - master

env:
  INFRA_REPOSITORY: https://github.com/thomazrd/tiggomark-infra.git
  CLUSTER_NAME: cluster
  INFRA_HOST: 20.195.163.70
  INFRA_PORT: 22

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Update Cluster
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.INFRA_SSH_HOST }}
          username: ${{ secrets.INFRA_SSH_USERNAME }}
          password: ${{ secrets.INFRA_SSH_PASSWORD }}
          port: ${{ env.INFRA_SSH_PORT }}
          script: |
           rm -rf tiggomark-infra
           git clone ${{ env.INFRA_REPOSITORY }}
           cd tiggomark-infra
           docker stack deploy -c docker-swarm.yml ${{ env.CLUSTER_NAME }}
           

